[package]
name = "audio_recorder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15"
wav = "1.0.0"
arraydeque = "0.5"
hound = "3.5"
chrono = "0.4"
paho-mqtt = "0.12"