[package]
name = "audio_recorder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
wav = "1.0.0"
arraydeque = "0.5.1"
hound = "3.4.0"
chrono = "0.4"