name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update Cargo
      run: |
        sudo apt-get install -y libasound2-dev
        sudo apt-get install -y libwebkit2gtk-4.0 
        cargo update
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test
